<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pratheep" failures="0" tests="2" name="com.TestNG.TestNG_timeout" time="5.025" errors="1" timestamp="2024-09-19T22:38:40 IST" skipped="1">
  <testcase classname="com.TestNG.TestNG_timeout" name="ApplicationLogut" time="5.025">
    <error message="Method com.TestNG.TestNG_timeout.ApplicationLogut() didn&#039;t finish within the time-out 5000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.TestNG.TestNG_timeout.ApplicationLogut() didn't finish within the time-out 5000
at java.base/java.lang.Thread.sleepNanos0(Native Method)
at java.base/java.lang.Thread.sleepNanos(Thread.java:491)
at java.base/java.lang.Thread.sleep(Thread.java:522)
at com.TestNG.TestNG_timeout.ApplicationLogut(TestNG_timeout.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </error>
  </testcase> <!-- ApplicationLogut -->
  <testcase classname="com.TestNG.TestNG_timeout" name="CloseBrowser">
    <skipped/>
  </testcase> <!-- CloseBrowser -->
</testsuite> <!-- com.TestNG.TestNG_timeout -->
